In [1]:
import numpy as np

In [2]:
def sig(z):
    return 1/(1 + np.exp(-z))

In [3]:
def derSig(z):
    return sig(z)* (1 - sig(z))

In [7]:
X = np.array([[0,0], [0,1], [1,0], [1,1]])
Y = np.array([0,1,1,0]).reshape((4,1))
X.shape, Y.shape

((4, 2), (4, 1))

In [8]:
wh = 2 * np.random.random((2, 2)) - 1
wout = 2 * np.random.random((2, 1)) - 1
bh = 2 * np.random.random((1,2)) - 1
bout = 2 * np.random.random((1,1)) - 1

In [15]:
wh, bh, Y

(array([[-0.36013321, -0.92300157],
        [ 0.66475489, -0.11568958]]),
 array([[0.57121073, 0.9647995 ]]),
 array([[0],
        [1],
        [1],
        [0]]))

In [6]:
def forward(x, wh, wout, bh, bout):
    output0 = x
    hidden_layer_input = np.dot(output0, wh) + bh
    hidden_layer_output = sig(hidden_layer_input)
    
    output_layer_input = np.dot(hidden_layer_output, wout) + bout
    final_output = sig(output_layer_input)
    return final_output

In [7]:
def train(x, y, wh, wout, bh, bout, epochs, lr):
    for i in range(epochs):
        output0 = x
        hidden_layer_input = np.dot(output0, wh) + bh
        hidden_layer_output = sig(hidden_layer_input)
    
        output_layer_input = np.dot(hidden_layer_output, wout) + bout
        final_output = sig(output_layer_input)
        
        first_term_output = final_output - y
        second_term_output = derSig(output_layer_input)
        first_two_output = first_term_output*second_term_output
        
        first_term_hidden_layer = np.dot(first_two_output, wout.T)
        second_term_hidden_layer = derSig(hidden_layer_input)
        first_two_hidden = first_term_hidden_layer*second_term_hidden_layer
        
        
        changes_wh = np.dot(output0.T, first_two_hidden)
        changes_wout = np.dot(hidden_layer_output.T, first_two_output)
        
        changes_bh = np.sum(first_two_hidden, axis = 0)
        change_bout = np.sum(first_two_output, axis = 0)
        
        wh = wh - lr*changes_wh
        wout = wout - lr*changes_wout
        bout = bout - lr*change_bout
        bh = bh - lr * changes_bh
        
    return wh, wout, bh, bout

In [8]:
wh, wout, bh, bout = train(X, Y, wh, wout,bh, bout, 10000, 1)

In [9]:
forward(X, wh, wout, bh, bout)

array([[0.01305955],
       [0.98879984],
       [0.98880337],
       [0.01156505]])

In [10]:
wout,bout

(array([[-10.99362352],
        [ 10.26688979]]), array([[-4.77172355]]))

In [11]:
wh, bh

(array([[4.81407811, 6.85309339],
        [4.81302143, 6.84825276]]), array([[-7.37955969, -3.07453628]]))

In [12]:
a = np.array([[1,2,3],[4,5,6]])
b = np.sum(a, axis = 0, keepdims=True)
b,b.shape

(array([[5, 7, 9]]), (1, 3))